# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'practice.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Stravaapi import years


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(587, 426)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(200, 110, 60, 16))
        self.label1.setText("")
        self.label1.setObjectName("label1")
        self.yearcombobox = QtWidgets.QComboBox(self.centralwidget)
        self.yearcombobox.setGeometry(QtCore.QRect(10, 40, 101, 22))
        self.yearcombobox.setObjectName("yearcombobox")

        for i in range(len(years) + 1):
            self.yearcombobox.addItem("")
            
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.actComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.actComboBox.setGeometry(QtCore.QRect(270, 40, 101, 22))
        self.actComboBox.setObjectName("actComboBox")
        self.actComboBox.addItem("")
        self.actComboBox.addItem("")
        self.actComboBox.addItem("")
        self.actComboBox.addItem("")
        self.actComboBox.setItemText(3, "")
        self.monthComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.monthComboBox.setGeometry(QtCore.QRect(140, 40, 101, 22))
        self.monthComboBox.setObjectName("monthComboBox")
        self.monthComboBox.addItem("")
        self.monthComboBox.addItem("")
        self.monthComboBox.addItem("")
        self.monthComboBox.addItem("")
        self.monthComboBox.addItem("")
        self.monthComboBox.addItem("")
        self.monthComboBox.addItem("")
        self.monthComboBox.addItem("")
        self.monthComboBox.addItem("")
        self.monthComboBox.addItem("")
        self.monthComboBox.addItem("")
        self.monthComboBox.addItem("")
        self.monthComboBox.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 587, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.yearcombobox.setItemText(0, _translate("MainWindow", "Year"))

        for i in range(len(years)):
            self.yearcombobox.setItemText(i + 1, _translate("MainWindow", years[i]))

        self.label.setText(_translate("MainWindow", "Select a Year to View Statistics for:"))
        self.actComboBox.setItemText(0, _translate("MainWindow", "All Activities"))
        self.actComboBox.setItemText(1, _translate("MainWindow", "Bike"))
        self.actComboBox.setItemText(2, _translate("MainWindow", "Run"))
        self.monthComboBox.setItemText(0, _translate("MainWindow", "All Months"))
        self.monthComboBox.setItemText(1, _translate("MainWindow", "January"))
        self.monthComboBox.setItemText(2, _translate("MainWindow", "Feburary"))
        self.monthComboBox.setItemText(3, _translate("MainWindow", "March"))
        self.monthComboBox.setItemText(4, _translate("MainWindow", "April"))
        self.monthComboBox.setItemText(5, _translate("MainWindow", "May"))
        self.monthComboBox.setItemText(6, _translate("MainWindow", "June"))
        self.monthComboBox.setItemText(7, _translate("MainWindow", "July"))
        self.monthComboBox.setItemText(8, _translate("MainWindow", "August"))
        self.monthComboBox.setItemText(9, _translate("MainWindow", "Sepember"))
        self.monthComboBox.setItemText(10, _translate("MainWindow", "October"))
        self.monthComboBox.setItemText(11, _translate("MainWindow", "November"))
        self.monthComboBox.setItemText(12, _translate("MainWindow", "December"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
