# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'practice.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Stravaapi import years, activitytypes, stravaposts

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(587, 426)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(200, 110, 60, 16))
        self.label1.setText("")
        self.label1.setObjectName("label1")
        self.yearcombobox = QtWidgets.QComboBox(self.centralwidget)
        self.yearcombobox.setGeometry(QtCore.QRect(10, 40, 101, 22))
        self.yearcombobox.setObjectName("yearcombobox")

        for i in range(len(years) + 1):
            self.yearcombobox.addItem("")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.actComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.actComboBox.setGeometry(QtCore.QRect(270, 40, 101, 22))
        self.actComboBox.setObjectName("actComboBox")

        for i in range(len(activitytypes) + 1):
            self.actComboBox.addItem("")

        self.actComboBox.setItemText(3, "")
        self.monthComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.monthComboBox.setGeometry(QtCore.QRect(140, 40, 101, 22))
        self.monthComboBox.setObjectName("monthComboBox")
        self.monthComboBox.addItem("")
        self.monthComboBox.addItem("")
        self.monthComboBox.addItem("")
        self.monthComboBox.addItem("")
        self.monthComboBox.addItem("")
        self.monthComboBox.addItem("")
        self.monthComboBox.addItem("")
        self.monthComboBox.addItem("")
        self.monthComboBox.addItem("")
        self.monthComboBox.addItem("")
        self.monthComboBox.addItem("")
        self.monthComboBox.addItem("")
        self.monthComboBox.addItem("")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(60, 140, 471, 171))
        self.listWidget.setObjectName("listWidget")

        for i in range(len(activitytypes) + 1):
            item = QtWidgets.QListWidgetItem()
            item.setTextAlignment(QtCore.Qt.AlignCenter)
            item.setFlags(QtCore.Qt.ItemIsEnabled)
            self.listWidget.addItem(item)

        self.StatsButton = QtWidgets.QPushButton(self.centralwidget)
        self.StatsButton.setGeometry(QtCore.QRect(440, 20, 91, 51))
        self.StatsButton.setObjectName("StatsButton")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 587, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())

        self.StatsButton.clicked.connect(self.pressed)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.yearcombobox.setItemText(0, _translate("MainWindow", "All"))

        for i in range(len(years)):
            self.yearcombobox.setItemText(i + 1, _translate("MainWindow", years[i]))

        self.label.setText(_translate("MainWindow", "Select a Year to View Statistics for:"))
        self.actComboBox.setItemText(0, _translate("MainWindow", "All Activities"))

        for i in range(len(activitytypes)):
            self.actComboBox.setItemText(i + 1, _translate("MainWindow", activitytypes[i]))

        self.monthComboBox.setItemText(0, _translate("MainWindow", "All Months"))
        self.monthComboBox.setItemText(1, _translate("MainWindow", "01"))
        self.monthComboBox.setItemText(2, _translate("MainWindow", "02"))
        self.monthComboBox.setItemText(3, _translate("MainWindow", "03"))
        self.monthComboBox.setItemText(4, _translate("MainWindow", "04"))
        self.monthComboBox.setItemText(5, _translate("MainWindow", "05"))
        self.monthComboBox.setItemText(6, _translate("MainWindow", "06"))
        self.monthComboBox.setItemText(7, _translate("MainWindow", "07"))
        self.monthComboBox.setItemText(8, _translate("MainWindow", "08"))
        self.monthComboBox.setItemText(9, _translate("MainWindow", "09"))
        self.monthComboBox.setItemText(10, _translate("MainWindow", "10"))
        self.monthComboBox.setItemText(11, _translate("MainWindow", "11"))
        self.monthComboBox.setItemText(12, _translate("MainWindow", "12"))

        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        #item = self.listWidget.item(0)
        #item.setText(_translate("MainWindow", "You traveled a total distnance of _ with Strava "))
        #item = self.listWidget.item(1)
        #item.setText(_translate("MainWindow", "You ran a totla distance of _ with Strava."))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.StatsButton.setText(_translate("MainWindow", "Show Stats"))

        self.menuFile.setTitle(_translate("MainWindow", "File"))

    def pressed(self):
        _translate = QtCore.QCoreApplication.translate
        total_dist = 0
        distances = []
        for i in activitytypes:
            distances.append(0) #appending a 0 for each activitytype
        #the first 0 with correspond to the distance for the first activitytype
        #the second 0 will correspond to the distance for the second activitytype, etc

        for i in range(len(stravaposts['distance'])):
            if (stravaposts.at[i,'start_date_local'][:4] == self.yearcombobox.currentText() or self.yearcombobox.currentText() == "All") and (stravaposts.at[i,'start_date_local'][5:7] == self.monthComboBox.currentText() or self.monthComboBox.currentText() == "All Months"):
                total_dist += stravaposts.at[i,'distance']

                for j in range(len(activitytypes)):
                    if stravaposts.at[i,'type'] == activitytypes[j]:
                        distances[j] += stravaposts.at[i,'distance']

        total_dist /= 1609.344 #converting meters to miles

        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "You traveled a total distance of " + str(round(total_dist,2)) + " miles with Strava."))
        #item = self.listWidget.item(1)
        #item.setText(_translate("MainWindow", "You ran a totla distance of _ with Strava."))
        for i in range(len(distances)):
            distances[i] /= 1609.344
            item = self.listWidget.item(i + 1)
            item.setText(_translate("MainWindow", "Your " + activitytypes[i]+ " total with Strava was "+ str(round(distances[i],2)) + " miles."))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
